### ISSUE TITLE
想问下大佬你能否给出ProxySQL对接MHA时，相关表配置示例

### ISSUE THREAD

**Issue by hadesfeng** [arstercz/mha_switch#1]
mysql_replication_hostgroups
mysql_servers
mysql_users

**Comment by arstercz** [comment]
hi @hadesfeng  proxysql 的配置可以参考我以前写的文章 [proxysql 配置测试](https://blog.arstercz.com/proxysql-%E4%BB%8B%E7%BB%8D%E5%8F%8A%E6%B5%8B%E8%AF%95%E4%BD%BF%E7%94%A8/), 现在应该很多选项参数改变了很多, 不过大体的配置不会怎么变动.

**Comment by hadesfeng** [comment]
谢谢大佬，跟我自己弄的配置差不多，我是通过命令操作，你的是通过配置文件，殊途同归。
